# Generated by Django 3.2 on 2021-04-23 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0002_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='folder',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookmarks.folder'),
        ),
    ]
